name: Build Vortex App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            sep: ';'
            icon: 'assets/icon.ico'
            ext: 'exe'
          - os: macos-latest
            sep: ':'
            icon: 'assets/icon.icns' 
            ext: 'app'
          - os: ubuntu-latest
            sep: ':'
            icon: 'assets/icon.png'
            ext: ''

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup FFmpeg
        run: python get_ffmpeg.py

      - name: Build Application
        run: pyinstaller --name Vortex --onefile --windowed --clean --noconfirm --icon="${{ matrix.icon }}" --add-data "assets${{ matrix.sep }}assets" main.py

      
      - name: Cleanup macOS Build
        if: matrix.os == 'macos-latest'
        run: |
          rm -f dist/Vortex
        

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Vortex-App-${{ matrix.os }}
          
          path: dist/Vortex.${{ matrix.ext }}