name: Build Vortex App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    
    
   
    - name: Download FFmpeg (Windows)
      if: runner.os == 'Windows'
      run: |
        curl -L -o assets/ffmpeg.exe https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.exe

   
    - name: Download FFmpeg (Mac/Linux)
      if: runner.os != 'Windows'
      run: |
        
        curl -L -o assets/ffmpeg https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl
        chmod +x assets/ffmpeg

    # --------------------------------------

    - name: Build Windows EXE
      if: runner.os == 'Windows'
      run: |
        pyinstaller --name Vortex --onefile --windowed --icon=assets/icon.ico --add-data "assets;assets" main.py

    - name: Build macOS APP
      if: runner.os == 'macOS'
      run: |
        pyinstaller --name Vortex --onefile --windowed --icon=assets/icon.icns --add-data "assets:assets" main.py

    - name: Build Linux Binary
      if: runner.os == 'Linux'
      run: |
        pyinstaller --name Vortex --onefile --windowed --icon=assets/icon.png --add-data "assets:assets" main.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Vortex-${{ matrix.os }}
        path: dist/