name: Build Vortex App


on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
   
    - uses: actions/checkout@v3

   
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3.
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. ffmpeg
    - name: Grant permissions to FFmpeg (Mac/Linux)
      if: runner.os != 'Windows'
      run: |
        chmod +x assets/ffmpeg || true

    # 5Windows
    - name: Build Windows EXE
      if: runner.os == 'Windows'
      run: |
        pyinstaller --name Vortex --onefile --windowed --icon=assets/icon.ico --add-data "assets;assets" main.py

    # 6.macOS
    - name: Build macOS APP
      if: runner.os == 'macOS'
      run: |
        pyinstaller --name Vortex --onefile --windowed --icon=assets/icon.icns --add-data "assets:assets" main.py

    # 7. Linux
    - name: Build Linux Binary
      if: runner.os == 'Linux'
      run: |
        
        pyinstaller --name Vortex --onefile --windowed --icon=assets/icon.png --add-data "assets:assets" main.py

    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Vortex-${{ matrix.os }}
        path: dist/